nicks = [
  'Foxkrak',
  'junior72',
  'BLACK SNIPER',
  'stromrakka',
  'igor89araujo',
  'Frost',
  'WBPinto',
  'xxxhygorxxx',
  'chuck.mauricio',
  'tutancamon',
  'matheusass',
  '- Os Rauls',
  'sdrago',
  'joloirao',
  'Leo17Matador',
  'Mano Tse-Tung',
  'Manowar',
  'Adriano Ferraz'
]
