nicks = [
  'Foxkrak',
  'o furquilhador',
  'COELHO GORDO',
  'ailton-o-grande',
  'design.inthedark',
  'overlogic2',
  'osmar11',
  'chuck.mauricio',
  'M E S T R E -',
  'BLACK SNIPER',
  'kairoSiqueira',
  'P.a.L.e.R.m.O',
  'mateus demoon',
  'Arqueiro Verde',
  '-BERLIM',
  'Senhor Gragas',
  'maarlosb',
  'LaTiNoS',
  'toffany',
  'assuma',
  'Hell Wars',
  'zFlame',
  'junior72',
  'Atopocentrismo',
  'Pintor rx',
  'Brooksfield',
  'KinTetsu',
  'erickloliveira',
  'oLucifer',
  '- The Last NOoB',
  'PEDRA PRETA',
  'nightmarengar',
  'Paulo cesar sousa santos',
  '- Os Rauls',
  'fabi.tribal',
  'Frost',
  'stromrakka',
  'Kinalskera',
  'carlitos170',
  'MarceloCJr -',
  'istanlley',
  'brenokaiser',
  'kmkz',
  'Demolidor11'
  ',matheusass',
  'AlexSnow',
  'WBPinto',
  'brennooh',
  'igor89araujo',
  'tutancamon',
  'Arabaz',
  'sdrago',
  'ShockEng',
  'Thiag0vill',
  'Nagato',
  'macedox',
  'Volk',
  'Lord Breno',
  'DidierRei11',
  'Rei O Bravo',
  'Pixxote',
  'xxxhygorxxx',
  'GbBigRola'
]
