nicks = [
  {nick:'Foxkrak',disp:'all'},
  {nick:'junior72',disp:'all'},
  {nick:'BLACK SNIPER',disp:'all'},
  {nick:'stromrakka',disp:'all'},
  {nick:'igor89araujo',disp:'all'},
  {nick:'Frost',disp:'all'},
  {nick:'WBPinto',disp:'all'},
  {nick:'xxxhygorxxx',disp:'all'},
  {nick:'chuck.mauricio',disp:'all'},
  {nick:'tutancamon',disp:'all'},
  {nick:'matheusass',disp:'all'},
  {nick:'- Os Rauls',disp:'all'},
  {nick:'sdrago',disp:'all'},
  {nick:'joloirao',disp:'all'},
  {nick:'Leo17Matador',disp:'all'},
  {nick:'Mano Tse-Tung',disp:'autoup'},
  {nick:'Manowar',disp:'autoup'},
]
